### ISSUE TITLE
Download feature

### ISSUE THREAD

**Issue by krishna2206** [PietroJomini/zeniba#1]
Hey, I have a question regarding the download feature on your program.
Have you already tested it ? Was it be able to download the book successfuly ? 
Because I'm also working on a download feature like yours but mine failed to download books, after sending request to the book download url (```URL + "/dl/" + zid"```), mine redirects to the book url plus a parameter **"?WrongHash"** so I'm curious if you have been able to solve this problem. Thank you !

**Comment by PietroJomini** [comment]
Hi, I'll start by saying that i haven't tested the feature well enough. I've tried with a couple of books while coding it, but an extensive test suite is yet in the TODO list!

Now, I've noticed that by adding the `User-Agent` header and allowing redirects the content is successfully retrieved. I'm not still sure why that happens, but maybe it's just a check that the official API does on the requests (?).
I've set the `User-Agent` header to the latest Mozilla, but by browsing a couple of similar projects it seems that any client works fine.

Without the `User-Agent` header (and by using the download id, not the book id) z-library returns a 410 with a `Onion-Location` header, but anything i tried by following that path hasn't worked.

The `WrongHash` parameters suggest that you sent a wrong `id`, maybe you used the book id instead of the download id? I plan of investigating more in the id's format, as they seem to be made of two chunks, but I didn't had time yet.

**Comment by krishna2206** [comment]
Thank you for responding, actually I confused the Book ID and that of Download ID (the one we get in the Download button), it's working now , thank you !  I think I will use your package since it works well.

Why not use an integrated downloader into the package and possibly with a progress bar ? since on the Tor network the download is slow, it would be good to be able to see the download progress 😉

**Comment by PietroJomini** [comment]
Thank you for the feedback! And I'm happy that you solved your issue. 
Regarding the progress bar, it's actually a good idea. I plan on implementing soon a good CLI interface to the main core, and i think it's better to keep the core "output-agnostic" and add the bar (and other fancy stuff like that) directly in the CLI.
